### ISSUE TITLE
Update themes to new design

### ISSUE THREAD

**Issue by polyamAdmin** [polyamspace/mastodon#484]
### Pitch

- [x] #483 
- [x] #485 
- [ ] Update or remove Oatstodon[^2]

[^1]: I suggest using `darken($purple2, 4%);` as background color as it is easier on the eyes.

[^2]: Oatstodon is a borderless design and the new design heavily relies on borders to distinct elements.

### Motivation

The new design is simpler and easier on eyes.
Also the themes do need a cleanup.

**Comment by AjaySDwivedi1** [comment]
Can I work on this issue?

**Comment by polyamAdmin** [comment]
Sure

**Comment by AjaySDwivedi1** [comment]
If you don't mind me asking, what file do I need to change or what do I need to update? Sorry to ask I'm just a little lost.

**Comment by polyamAdmin** [comment]
For the FairyFloss themes the following files:
- `app/javascript/flavours/polyam/styles/fairy-floss.scss`
- `app/javascript/flavours/polyam/styles/fairy-floss/variables.scss`
- `app/javascript/flavours/polyam/styles/fairy-floss/diff.scss`

(You can use #485 as a starting point for FairyFloss)

For Oatstodon theme:
- `app/javascript/flavours/polyam/styles/oatstodon.scss`
- `app/javascript/flavours/polyam/styles/oatstodon/variables.scss`
- `app/javascript/flavours/polyam/styles/oatstodon/diff.scss`

You can look at #483 for reference, but essentially some of the style overrides are outdated and no longer needed and others are missing.

You likely want to set up a dev environment to preview changes.
Instructions for that can be found there: https://docs.joinmastodon.org/dev/setup/
(That guide is a bit outdated and incomplete though, but I didn't write it :/)

**Comment by AjaySDwivedi1** [comment]
Thank you! I'll try my best!

**Comment by AjaySDwivedi1** [comment]
What' the new theme suppose to be/look like?

**Comment by polyamAdmin** [comment]
Good question...
Essentially it should end up looking like the default or homogay theme, just with different colors and preserving some theme specific details if that makes sense

**Comment by AjaySDwivedi1** [comment]
Hey sorry but I'm not able to work on this issue anymore. I'm really sorry.

**Comment by polyamAdmin** [comment]
That's okay
Thank you for offering to help anyway
